### ISSUE TITLE
教程底部的 question 翻译需要去掉

### ISSUE THREAD

**Issue by hiETsang** [SwiftGGTeam/swiftgg-trans-plugin#6]

**Comment by JacobMao** [comment]
是这种 question 吗？

<img width="1030" alt="Screenshot 2023-07-10 at 10 47 09" src="https://github.com/SwiftGGTeam/swiftgg-trans-plugin/assets/5173117/85913017-974e-4367-81a4-76518365859b">

**Comment by hiETsang** [comment]
@JacobMao 是的
