### ISSUE TITLE
插件的 UI 调整，新增分类

### ISSUE THREAD

**Issue by hiETsang** [SwiftGGTeam/swiftgg-trans-plugin#8]

**Comment by hiETsang** [comment]
设计稿链接：[figma](https://www.figma.com/file/T5IUaDGEA8ugv1ZzDqcLu0/swiftGG-%E8%AE%BE%E8%AE%A1?type=design&node-id=45:61&mode=design&t=HytbmmkruqK2CPi5-1)，仅供参考，扩展列表可以用选择器的形式

**Comment by yongfrank** [comment]
<img width="616" alt="image" src="https://github.com/SwiftGGTeam/swiftgg-trans-plugin/assets/38122319/2070ab50-47dc-4fb1-bda3-0dbc494c6b23">
<img width="524" alt="image" src="https://github.com/SwiftGGTeam/swiftgg-trans-plugin/assets/38122319/1d9134cd-1cee-4683-9595-240f5cf805ac">
